using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Specialized;
// <copyright file="UriHelperTest.BuildUri.g.cs" company="lotosbin">Copyright ? 2013</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace BinbinDotNetOpenAuth.AspNet.Clients
{
    public partial class UriHelperTest
    {
[TestMethod]
[PexGeneratedBy(typeof(UriHelperTest))]
[PexRaisedException(typeof(ArgumentNullException))]
public void BuildUriThrowsArgumentNullException660()
{
    Uri uri;
    uri = this.BuildUri((string)null, (NameValueCollection)null, (string)null);
}
    }
}
